# Generated by Django 5.0.7 on 2024-07-16 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                ("sobrenome", models.CharField(max_length=50, unique=True)),
                ("foto", models.ImageField(blank=True, null=True, upload_to="fotos/")),
                ("cpf", models.CharField(max_length=14)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                ("descricao", models.CharField(blank=True, max_length=280, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Chamada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("horario", models.TimeField()),
                ("duracao", models.DurationField()),
                (
                    "contato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.contato"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endereco", models.EmailField(max_length=255)),
                (
                    "contato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.contato"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contato",
            name="grupos",
            field=models.ManyToManyField(to="app.grupo"),
        ),
        migrations.CreateModel(
            name="Pesquisa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.contato"
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.grupo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Telefone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=20)),
                (
                    "contatos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.contato"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("senha", models.CharField(max_length=128)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.email"
                    ),
                ),
                (
                    "telefone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.telefone"
                    ),
                ),
            ],
        ),
    ]
