# Generated by Django 5.0.7 on 2024-07-18 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telefone',
            old_name='contatos',
            new_name='contato',
        ),
    ]
