# Generated by Django 5.0.7 on 2024-07-22 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_contato_options_chamada_email_pesquisa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='endereco',
            new_name='email',
        ),
    ]
